# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: trailing-whitespace
        exclude: ^sandbox|(.el|.svg|.tex|pseudoxml.txt)$
    -   id: end-of-file-fixer
        exclude: ^sandbox|(.svg|docutils/test/data/utf-16-le-sig.txt)$

-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4  # Docutils' ``.flake8`` configuration files do not work with Flake8 >=6
    hooks:
    -   id: flake8
